-- =====================================================================
-- 0012_limpieza_datos_prueba.sql
--
-- OPCIONAL — solo lectura/borrado puntual, correr a mano en el SQL Editor
-- si quieres limpiarlo. No se incluyó por pedido explícito, pero quedó
-- detectado en el diagnóstico de la conversación: V-00000000 / "John Doe"
-- es un registro de prueba contaminando los contadores y reportes.
--
-- 1) Revisa primero qué vas a borrar:
--    SELECT * FROM asistencias_diarias WHERE cedula_docente = 'V-00000000';
--
-- 2) Si confirmas que es prueba, bórralo:
--    DELETE FROM asistencias_diarias WHERE cedula_docente = 'V-00000000';
--
-- 3) Si además quieres fusionar los dos registros de Luis Solorzano
--    (V-18341488, correcto, con su día completo de entrada/salida) y
--    descartar el typo (V-18341588, entrada+salida a 20s de diferencia):
--    SELECT * FROM asistencias_diarias WHERE cedula_docente = 'V-18341588';
--    DELETE FROM asistencias_diarias WHERE cedula_docente = 'V-18341588';
--
-- Verifica siempre con el SELECT antes de correr el DELETE.
-- =====================================================================
